from __future__ import annotations

import logging
import os
import re
import sqlite3
import threading
import uuid
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

try:
    import psycopg
    from psycopg.rows import dict_row
except ModuleNotFoundError:
    psycopg = None
    dict_row = None

logger = logging.getLogger("shef.usage")

APP_DIR = Path(__file__).resolve().parent
DEFAULT_USAGE_DB_PATH = APP_DIR / ".local" / "shef_usage.sqlite3"
USAGE_SESSION_COOKIE = "shef_usage_session"

EVENT_TYPES = {
    "session_started",
    "chat_submitted",
    "recipe_options_shown",
    "recipe_selected",
    "image_uploaded",
    "audio_uploaded",
    "non_ingredient_upload_rejected",
    "chat_success",
    "chat_error",
}

TRUE_VALUES = {"1", "true", "yes", "on"}
SAFE_TEXT_RE = re.compile(r"[^a-zA-Z0-9 _./:-]")
SESSION_ID_RE = re.compile(r"^[a-zA-Z0-9_-]{8,80}$")

SQLITE_CREATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS usage_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TEXT NOT NULL,
    session_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    response_mode TEXT,
    model_provider TEXT,
    success INTEGER,
    attachment_type TEXT,
    status_code INTEGER,
    error_category TEXT,
    user_agent_family TEXT
)
"""

POSTGRES_CREATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS public.usage_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    session_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    response_mode TEXT,
    model_provider TEXT,
    success BOOLEAN,
    attachment_type TEXT,
    status_code INTEGER,
    error_category TEXT,
    user_agent_family TEXT,
    CONSTRAINT usage_events_event_type_check CHECK (
        event_type IN (
            'session_started',
            'chat_submitted',
            'recipe_options_shown',
            'recipe_selected',
            'image_uploaded',
            'audio_uploaded',
            'non_ingredient_upload_rejected',
            'chat_success',
            'chat_error'
        )
    )
)
"""

POSTGRES_ENABLE_RLS_SQL = "ALTER TABLE public.usage_events ENABLE ROW LEVEL SECURITY"

INDEX_SQL = {
    "sqlite": [
        "CREATE INDEX IF NOT EXISTS idx_usage_events_created_at ON usage_events(created_at)",
        "CREATE INDEX IF NOT EXISTS idx_usage_events_event_type ON usage_events(event_type)",
        "CREATE INDEX IF NOT EXISTS idx_usage_events_session_id ON usage_events(session_id)",
    ],
    "postgres": [
        "CREATE INDEX IF NOT EXISTS idx_usage_events_created_at ON public.usage_events (created_at)",
        "CREATE INDEX IF NOT EXISTS idx_usage_events_event_type ON public.usage_events (event_type)",
        "CREATE INDEX IF NOT EXISTS idx_usage_events_session_id ON public.usage_events (session_id)",
    ],
}

_init_lock = threading.Lock()
_initialized_storage_key: tuple[str, str] | None = None


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def new_session_id() -> str:
    return uuid.uuid4().hex


def usage_logging_enabled() -> bool:
    return os.getenv("SHEF_USAGE_LOGGING_ENABLED", "false").strip().lower() in TRUE_VALUES


def normalise_session_id(value: str | None) -> str:
    candidate = (value or "").strip()
    if SESSION_ID_RE.fullmatch(candidate):
        return candidate
    return new_session_id()


def usage_db_path() -> Path:
    raw_path = os.getenv("SHEF_USAGE_DB_PATH", "").strip()
    return Path(raw_path).expanduser() if raw_path else DEFAULT_USAGE_DB_PATH


def usage_database_url() -> str:
    return (
        os.getenv("SHEF_USAGE_DATABASE_URL", "").strip()
        or os.getenv("SUPABASE_DATABASE_URL", "").strip()
    )


def usage_storage_backend() -> str:
    return "postgres" if usage_database_url() else "sqlite"


def usage_storage_key() -> tuple[str, str]:
    backend = usage_storage_backend()
    if backend == "postgres":
        return backend, postgres_dsn()
    return backend, str(usage_db_path().resolve())


def postgres_dsn() -> str:
    url = usage_database_url()
    if not url:
        return ""

    parsed = urlsplit(url)
    query = dict(parse_qsl(parsed.query, keep_blank_values=True))
    query.setdefault("sslmode", "require")
    return urlunsplit(
        (
            parsed.scheme,
            parsed.netloc,
            parsed.path,
            urlencode(query),
            parsed.fragment,
        )
    )


def _connect() -> sqlite3.Connection:
    path = usage_db_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(path)
    connection.row_factory = sqlite3.Row
    return connection


@contextmanager
def _usage_connection() -> sqlite3.Connection:
    connection = _connect()
    try:
        yield connection
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


@contextmanager
def _postgres_connection():
    if psycopg is None:
        raise RuntimeError("Install psycopg to use Supabase/Postgres usage logging.")

    connection = psycopg.connect(postgres_dsn(), connect_timeout=10)
    try:
        yield connection
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def init_usage_db() -> None:
    global _initialized_storage_key

    if not usage_logging_enabled():
        return

    storage_key = usage_storage_key()
    if _initialized_storage_key == storage_key:
        return

    with _init_lock:
        if _initialized_storage_key == storage_key:
            return

        if usage_storage_backend() == "postgres":
            with _postgres_connection() as connection:
                cursor = connection.cursor()
                cursor.execute(POSTGRES_CREATE_TABLE_SQL)
                cursor.execute(POSTGRES_ENABLE_RLS_SQL)
                for sql in INDEX_SQL["postgres"]:
                    cursor.execute(sql)
            _initialized_storage_key = storage_key
            return

        with _usage_connection() as connection:
            connection.execute(SQLITE_CREATE_TABLE_SQL)
            for sql in INDEX_SQL["sqlite"]:
                connection.execute(sql)
        _initialized_storage_key = storage_key


def _safe_text(value: str | None, *, max_chars: int = 80) -> str | None:
    if value is None:
        return None
    cleaned = SAFE_TEXT_RE.sub("", str(value)).strip()
    return cleaned[:max_chars] or None


def rough_user_agent_family(user_agent: str | None) -> str:
    value = (user_agent or "").lower()
    if not value:
        return "Unknown"
    if "edg/" in value or "edge/" in value:
        return "Edge"
    if "firefox/" in value:
        return "Firefox"
    if "chrome/" in value or "chromium/" in value:
        return "Chrome"
    if "safari/" in value:
        return "Safari"
    if "curl/" in value:
        return "Curl"
    if "bot" in value or "crawler" in value or "spider" in value:
        return "Bot"
    return "Other"


def log_usage_event(
    *,
    event_type: str,
    session_id: str,
    response_mode: str | None = None,
    model_provider: str | None = None,
    success: bool | None = None,
    attachment_type: str | None = None,
    status_code: int | None = None,
    error_category: str | None = None,
    user_agent_family: str | None = None,
    created_at: str | None = None,
) -> bool:
    if not usage_logging_enabled():
        return False

    if event_type not in EVENT_TYPES:
        logger.warning("Skipped unknown usage event type: %s", event_type)
        return False

    values = (
        created_at or utc_now_iso(),
        normalise_session_id(session_id),
        event_type,
        _safe_text(response_mode, max_chars=40),
        _safe_text(model_provider, max_chars=80),
        None if success is None else bool(success),
        _safe_text(attachment_type, max_chars=20),
        status_code,
        _safe_text(error_category, max_chars=60),
        _safe_text(user_agent_family, max_chars=40),
    )

    try:
        init_usage_db()
        if usage_storage_backend() == "postgres":
            with _postgres_connection() as connection:
                cursor = connection.cursor()
                cursor.execute(
                    """
                    INSERT INTO public.usage_events (
                        created_at,
                        session_id,
                        event_type,
                        response_mode,
                        model_provider,
                        success,
                        attachment_type,
                        status_code,
                        error_category,
                        user_agent_family
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    """,
                    values,
                )
            return True

        sqlite_values = (
            *values[:5],
            None if success is None else int(success),
            *values[6:],
        )
        with _usage_connection() as connection:
            connection.execute(
                """
                INSERT INTO usage_events (
                    created_at,
                    session_id,
                    event_type,
                    response_mode,
                    model_provider,
                    success,
                    attachment_type,
                    status_code,
                    error_category,
                    user_agent_family
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                sqlite_values,
            )
        return True
    except Exception as exc:
        logger.warning("Usage event logging failed: %s", type(exc).__name__)
        return False


def empty_usage_summary() -> dict[str, Any]:
    return {
        "total_sessions": 0,
        "total_chats": 0,
        "recipe_selections": 0,
        "uploads": 0,
        "errors": 0,
        "recent_activity": [],
    }


def usage_summary(*, limit: int = 25) -> dict[str, Any]:
    if not usage_logging_enabled():
        return empty_usage_summary()

    init_usage_db()
    safe_limit = max(1, min(limit, 100))
    if usage_storage_backend() == "postgres":
        with _postgres_connection() as connection:
            cursor = connection.cursor(row_factory=dict_row)
            cursor.execute(
                """
                SELECT
                    COUNT(DISTINCT session_id) AS total_sessions,
                    SUM(CASE WHEN event_type = 'chat_submitted' THEN 1 ELSE 0 END) AS total_chats,
                    SUM(CASE WHEN event_type = 'recipe_selected' THEN 1 ELSE 0 END) AS recipe_selections,
                    SUM(CASE WHEN event_type IN ('image_uploaded', 'audio_uploaded') THEN 1 ELSE 0 END) AS uploads,
                    SUM(CASE WHEN event_type = 'chat_error' THEN 1 ELSE 0 END) AS errors
                FROM public.usage_events
                """
            )
            row = cursor.fetchone()
            cursor.execute(
                """
                SELECT
                    created_at,
                    session_id,
                    event_type,
                    response_mode,
                    model_provider,
                    success,
                    attachment_type,
                    status_code,
                    error_category,
                    user_agent_family
                FROM public.usage_events
                ORDER BY id DESC
                LIMIT %s
                """,
                (safe_limit,),
            )
            recent = cursor.fetchall()

        return {
            "total_sessions": int(row["total_sessions"] or 0),
            "total_chats": int(row["total_chats"] or 0),
            "recipe_selections": int(row["recipe_selections"] or 0),
            "uploads": int(row["uploads"] or 0),
            "errors": int(row["errors"] or 0),
            "recent_activity": [dict(item) for item in recent],
        }

    with _usage_connection() as connection:
        row = connection.execute(
            """
            SELECT
                COUNT(DISTINCT session_id) AS total_sessions,
                SUM(CASE WHEN event_type = 'chat_submitted' THEN 1 ELSE 0 END) AS total_chats,
                SUM(CASE WHEN event_type = 'recipe_selected' THEN 1 ELSE 0 END) AS recipe_selections,
                SUM(CASE WHEN event_type IN ('image_uploaded', 'audio_uploaded') THEN 1 ELSE 0 END) AS uploads,
                SUM(CASE WHEN event_type = 'chat_error' THEN 1 ELSE 0 END) AS errors
            FROM usage_events
            """
        ).fetchone()
        recent = connection.execute(
            """
            SELECT
                created_at,
                session_id,
                event_type,
                response_mode,
                model_provider,
                success,
                attachment_type,
                status_code,
                error_category,
                user_agent_family
            FROM usage_events
            ORDER BY id DESC
            LIMIT ?
            """,
            (safe_limit,),
        ).fetchall()

    return {
        "total_sessions": int(row["total_sessions"] or 0),
        "total_chats": int(row["total_chats"] or 0),
        "recipe_selections": int(row["recipe_selections"] or 0),
        "uploads": int(row["uploads"] or 0),
        "errors": int(row["errors"] or 0),
        "recent_activity": [dict(item) for item in recent],
    }
