create table if not exists public.usage_events (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    session_id text not null,
    event_type text not null,
    response_mode text,
    model_provider text,
    success boolean,
    attachment_type text,
    status_code integer,
    error_category text,
    user_agent_family text,
    constraint usage_events_event_type_check check (
        event_type in (
            'session_started',
            'chat_submitted',
            'recipe_options_shown',
            'recipe_selected',
            'image_uploaded',
            'audio_uploaded',
            'non_ingredient_upload_rejected',
            'chat_success',
            'chat_error'
        )
    )
);

alter table public.usage_events enable row level security;

create index if not exists idx_usage_events_created_at
    on public.usage_events (created_at);

create index if not exists idx_usage_events_event_type
    on public.usage_events (event_type);

create index if not exists idx_usage_events_session_id
    on public.usage_events (session_id);
